[workspace]
[package]
version = "0.1.0"
name = "reth-sp1"
edition = "2021"

[dependencies]
alloy-rlp = { version = "0.3", default-features = false }
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "v1.1.1" }
sp1-reth-primitives = { git = "https://github.com/succinctlabs/sp1-reth.git", branch = "ratan/try-new-revm" }

reth-primitives = { git = "https://github.com/sp1-patches/reth-new", branch = "ratan/feature-gate-secp256k1", default-features = false }
revm = { git = "https://github.com/sp1-patches/revm-new", branch = "ratan/secp256k1-on-v35", features = [
    "serde",
], default-features = false }
revm-primitives = { git = "https://github.com/sp1-patches/revm-new", branch = "ratan/secp256k1-on-v35", default-features = false }
bincode = "1.3.3"

[patch.crates-io]
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "v0.10.8" }
revm = { git = "https://github.com/sp1-patches/revm-new", branch = "ratan/secp256k1-on-v35" }
revm-primitives = { git = "https://github.com/sp1-patches/revm-new", branch = "ratan/secp256k1-on-v35" }

[features]
sp1 = []
